import Layout from '@/app/components/layout/Layout';
import '../pages/globals.css';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body><Layout>{children}</Layout></body>
    </html>
  )
}
